# Site settings
title: Adrian Sadłocha - blog
description: Myśli stukotem klawiatury przelane.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.sadlocha.eu" # the base hostname & protocol for your site
twitter_username: Necior
github_username: Necior
delimiter_char: •

# Build settings
permalink: /:year/:month/:title/
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
future: false
